LabkaDB2/Models/Car.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace LabkaDB2.Models;

public partial class Car : Entity
{
    public int Id { get; set; }
    [Display(Name = "Модель")]
    public int ModelId { get; set; }
    [Display(Name = "Зона каршерінгу")]
    public int Cszid { get; set; }

    [Display(Name = "Орендується")]
    public bool IsRented { get; set; }

    [Display(Name = "Рік виготовлення")]
    public DateOnly ProduceYear { get; set; }
    [Display(Name = "Дата тех.огляду")]
    public DateOnly? TechInspirationDate { get; set; }
    [Display(Name = "Колір")]
    public string Color { get; set; } = null!;

    [Display(Name = "Зона")]
    public virtual CarSharingZone Csz { get; set; } = null!;

    [Display(Name = "Модель")]
    public virtual Model Model { get; set; } = null!;

    public virtual ICollection<Rent> Rents { get; set; } = new List<Rent>();
}

LabkaDB2/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LabkaDB2;
using LabkaDB2.Models;

namespace LabkaDB2.Controllers
{
    public class CarsController : Controller
    {
        private readonly CarSharingDbContext _context;

        public CarsController(CarSharingDbContext context)
        {
            _context = context;
        }

        // GET: Cars
        public async Task<IActionResult> Index()
        {
            var carSharingDbContext = _context.Cars.Include(c => c.Csz).Include(c => c.Model);
           

       
            return View(await carSharingDbContext.ToListAsync());
        }

        public async Task<IActionResult> CarsByTown()
        {
            var carSharingDbContext = _context.Cars.Include(c => c.Csz).Include(c => c.Model);



            return View(await carSharingDbContext.ToListAsync());
        }
        public async Task<IActionResult> CarsByUser()
        {
            var carSharingDbContext = _context.Cars.Include(c => c.Csz).Include(c => c.Model);



            return View(await carSharingDbContext.ToListAsync());
        }
        
        public async Task<IActionResult> CarsByBrand()
        {
            var carSharingDbContext = _context.Cars.Include(c => c.Csz).Include(c => c.Model);



            return View(await carSharingDbContext.ToListAsync());
        }


        public async Task<IActionResult> CarsNotRentedByUsersWhoRentedCar()
        {
            var carSharingDbContext = _context.Cars.Include(c => c.Csz).Include(c => c.Model);



            return View(await carSharingDbContext.ToListAsync());
        }


        public async Task<ActionResult<List<int>>> SearchByTown(string town)
        {
            var carIds = await _context.Cars
            .FromSqlRaw("SELECT c.Id FROM Cars c INNER JOIN CarSharingZones cz ON c.CSZID = cz.Id WHERE cz.Town = {0}", town)
            .Select(c => c.Id)
            .ToListAsync();

            return Json(carIds);

        }
        public async Task<ActionResult<List<Car>>> SearchCarsNotRentedByUsersWhoRentedCar(int carId)
        {
            var cars = await _context.Cars
                .FromSqlRaw(@"
                SELECT c.*
                FROM Cars c
                WHERE c.ID NOT IN (
                    SELECT DISTINCT r1.carID
                    FROM Rents r1
                    WHERE r1.custID IN (
                        SELECT r2.custID
                        FROM Rents r2
                        WHERE r2.carID = {0}
                    )
                )
            ", carId)
                .AsNoTracking()
                .Select(c=> c.Id)
                .ToListAsync();

            return Json(cars);
        }
    
    public async Task<ActionResult<List<int>>> SearchByBrand(string brand)
        {
            var carIds = await _context.Cars
            .FromSqlRaw("SELECT c.* FROM Cars c INNER JOIN Models m ON c.ModelId = m.Id WHERE m.Brand = {0}", brand)
            .Select(c => c.Id)
            .ToListAsync();

            return Json(carIds);

        }
        public async Task<ActionResult<List<int>>> SearchByUser(int id)
        {
            var carIds = await _context.Cars
            .FromSqlRaw("SELECT c.Id FROM Cars c INNER JOIN Rents r ON c.ID = r.carID WHERE r.custID = {0}", id)
            .Select(c => c.Id)
            .ToListAsync();

            return Json(carIds);

        }

        

        // GET: Cars/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Cars
                .Include(c => c.Csz)
                .Include(c => c.Model)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        public ActionResult GetAllCars()
        {
            return Json(_context.Cars);
        }

        // GET: Cars/Create
        public IActionResult Create()
        {
            ViewData["Cszid"] = new SelectList(_context.CarSharingZones.Select(c => new { Text = $"{c.Town} {c.Id}", Value = c.Id }), "Value", "Text");


            ViewData["ModelId"] = new SelectList(_context.Models.Select(c => new { Text = $"{c.ModelName} ({c.Id})", Value = c.Id }), "Value", "Text");
            
            return View();
        }

        // POST: Cars/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ModelId,Cszid,IsRented,ProduceYear,TechInspirationDate,Color")] Car car)
        {
            ModelState.Remove("Csz");
            ModelState.Remove("Model");
            if (ModelState.IsValid)
            {
                _context.Add(car);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Cszid"] = new SelectList(_context.CarSharingZones, "Id", "Id", car.Cszid);
            ViewData["ModelId"] = new SelectList(_context.Models, "Id", "Id", car.ModelId);
            return View(car);
        }

        // GET: Cars/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Cars.FindAsync(id);
            if (car == null)
            {
                return NotFound();
            }
            
            ViewData["Cszid"] = new SelectList(_context.CarSharingZones.Select(c => new { Text = $"{c.Town} {c.Id}", Value = c.Id }), "Value", "Text");
            
            
            ViewData["ModelId"] = new SelectList(_context.Models.Select(c => new {Text = $"{c.ModelName} ({c.Id})", Value = c.Id}), "Value", "Text");
            return View(car);
        }

        // POST: Cars/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ModelId,Cszid,IsRented,ProduceYear,TechInspirationDate,Color")] Car car)
        {
            ModelState.Remove("Csz");
            ModelState.Remove("Model");

            if (id != car.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(car);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarExists(car.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Cszid"] = new SelectList(_context.CarSharingZones, "Id", "Id", car.Cszid);
            ViewData["ModelId"] = new SelectList(_context.Models, "Id", "Id", car.ModelId);
            return View(car);
        }

        // GET: Cars/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Cars
                .Include(c => c.Csz)
                .Include(c => c.Model)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // POST: Cars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var car = await _context.Cars.FindAsync(id);
            if (car != null)
            {
                _context.Cars.Remove(car);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CarExists(int id)
        {
            return _context.Cars.Any(e => e.Id == id);
        }
    }
}

LabkaDB2/Controllers/ModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LabkaDB2;
using LabkaDB2.Models;

namespace LabkaDB2.Controllers
{
    public class ModelsController : Controller
    {
        private readonly CarSharingDbContext _context;

        public ModelsController(CarSharingDbContext context)
        {
            _context = context;
        }

        // GET: Models
        public async Task<IActionResult> Index()
        {
            return View(await _context.Models.ToListAsync());
        }

        // GET: Models/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var model = await _context.Models
                .FirstOrDefaultAsync(m => m.Id == id);
            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        // GET: Models/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Models/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ModelName,NumOfSeats,IsAutomatic,EngineVolume,HasCooling,Brand,Type")] Model model)
        {
            if (ModelState.IsValid)
            {
                _context.Add(model);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: Models/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var model = await _context.Models.FindAsync(id);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        // POST: Models/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ModelName,NumOfSeats,IsAutomatic,EngineVolume,HasCooling,Brand,Type")] Model model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ModelExists(model.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: Models/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var model = await _context.Models
                .FirstOrDefaultAsync(m => m.Id == id);
            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        // POST: Models/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var model = await _context.Models.FindAsync(id);
            if (model != null)
            {
                _context.Models.Remove(model);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ModelExists(int id)
        {
            return _context.Models.Any(e => e.Id == id);
        }
    }
}

LabkaDB2/Views/Cars/CarsByBrand.cshtml
@model IEnumerable<LabkaDB2.Models.Car>

@{
    ViewData["Title"] = "CarsByBrand";
}

<h1>Авто певного бренду</h1>
<p>
    <a asp-controller="Cars" asp-action="Index">Повернутись до меню</a>
</p>
<p>
    <a asp-action="CarsByBrand">Оновити</a>
</p>
<form id="myForm" onsubmit="handleSubmit(event)">
    <div>
        <label for="Brand">Бренд:</label>
        <input type="text" id="Brand" name="Brand" required>
    </div>
    <div>
        <button type="submit">Пошук</button>
    </div>
</form>
<style>
    .close {
        display: none;
    }
</style>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsRented)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProduceYear)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TechInspirationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Color)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Csz)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Model)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody id="car-table">
        @foreach (var item in Model)
        {
            <tr id=@item.Id>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsRented)
                </td>
                <td>
                    @item.ProduceYear.Year
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TechInspirationDate)
                </td>
                <td>
                    <div style="width: 15px; height: 15px; border-radius: 50%; margin-left:10px; border: 1px solid black; background: @item.Color"></div>
                </td>
                <td>
                    <a asp-controller="CarSharingZones" asp-action="Details" asp-route-id=@item.Csz.Id>@Html.DisplayFor(modelItem => item.Csz.Town) @Html.DisplayFor(modelItem => item.Csz.Id)</a>
                </td>
                <td>
                    <a asp-controller="Models" asp-action="Details" asp-route-id=@item.Model.Id>@Html.DisplayFor(modelItem => item.Model.ModelName)</a>
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Редагувати</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Деталі</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Видалити</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    

    function handleSubmit(event) {
        event.preventDefault();

        const inputBrand = document.getElementById('Brand').value;

        const queryParams = new URLSearchParams({
            brand: inputBrand
        });

        fetch(`SearchByBrand?${queryParams.toString()}`, {
            method: 'GET',
            headers: {
                'Accept': 'application/json'
            },
        }).then(response => response.json())
            .then(data => {
                console.log(data)


                const carTable = document.getElementById('car-table');
                const children = carTable.children;

                for (let i = 0; i < children.length; i++) {
                    children[i].classList.remove('close');
                }

                for (let i = 0; i < children.length; i++) {
                    const child = children[i];
                    const childId = parseInt(child.id, 10);

                    if (!data.includes(childId)) {
                        child.classList.add('close');
                    }
                }
            })
            .catch(error => console.error('Не вдається здійснити пошук.', error));
    }
</script>

LabkaDB2/Views/Cars/CarsByTown.cshtml
@model IEnumerable<LabkaDB2.Models.Car>

@{
    ViewData["Title"] = "CarsByTown";
}

<h1>Авто в певному місті</h1>
<p>
<a asp-controller="Cars" asp-action="Index">Повернутись до меню</a>
</p>
<p>
<a asp-action="CarsByTown">Оновити</a>
</p>
<form id="myForm" onsubmit="handleSubmit(event)">
    <div>
        <label for="Town">Місто:</label>
        <input type="text" id="Town" name="Town" required>
    </div>
    <div>
        <button type="submit">Пошук</button>
    </div>
</form>
<style>
    .close {
        display: none;
    }
</style>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsRented)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProduceYear)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TechInspirationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Color)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Csz)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Model)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody id="car-table">
        @foreach (var item in Model)
        {
            <tr id=@item.Id>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsRented)
                </td>
                <td>
                    @item.ProduceYear.Year
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TechInspirationDate)
                </td>
                <td>
                    <div style="width: 15px; height: 15px; border-radius: 50%; margin-left:10px; border: 1px solid black; background: @item.Color"></div>
                </td>
                <td>
                    <a asp-controller="CarSharingZones" asp-action="Details" asp-route-id=@item.Csz.Id>@Html.DisplayFor(modelItem => item.Csz.Town) @Html.DisplayFor(modelItem => item.Csz.Id)</a>
                </td>
                <td>
                    <a asp-controller="Models" asp-action="Details" asp-route-id=@item.Model.Id>@Html.DisplayFor(modelItem => item.Model.ModelName)</a>
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Редагувати</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Деталі</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Видалити</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    

    function handleSubmit(event) {
        event.preventDefault();

        const inputTown = document.getElementById('Town').value;

        const queryParams = new URLSearchParams({
            town: inputTown
        });

        fetch(`SearchByTown?${queryParams.toString()}`, {
            method: 'GET',
            headers: {
                'Accept': 'application/json'
            },
        }).then(response => response.json())
            .then(data => {
                console.log(data)

                
                const carTable = document.getElementById('car-table');
                const children = carTable.children;

                for (let i = 0; i < children.length; i++) {
                    children[i].classList.remove('close');
                }
                
                for (let i = 0; i < children.length; i++) {
                    const child = children[i];
                    const childId = parseInt(child.id, 10);

                    if (!data.includes(childId)) {
                        child.classList.add('close');
                    }
                }
            })
            .catch(error => console.error('Не вдається здійснити пошук.', error));
    }
</script>

LabkaDB2/Views/Cars/CarsByUser.cshtml
@model IEnumerable<LabkaDB2.Models.Car>

@{
    ViewData["Title"] = "CarsByTown";
}

<h1>Авто які орендовувались користувачем</h1>
<p>
    <a asp-controller="Cars" asp-action="Index">Повернутись до меню</a>
</p>
<p>
    <a asp-action="CarsByUser">Оновити</a>
</p>
<form id="myForm" onsubmit="handleSubmit(event)">
    <div>
        <label for="UserId">Id Користувача(number):</label>
        <input type="text" id="UserId" name="UserId" required>
    </div>
    <div>
        <button type="submit">Пошук</button>
    </div>
</form>
<style>
    .close {
        display: none;
    }
</style>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsRented)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProduceYear)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TechInspirationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Color)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Csz)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Model)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody id="car-table">
        @foreach (var item in Model)
        {
            <tr id=@item.Id>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsRented)
                </td>
                <td>
                    @item.ProduceYear.Year
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TechInspirationDate)
                </td>
                <td>
                    <div style="width: 15px; height: 15px; border-radius: 50%; margin-left:10px; border: 1px solid black; background: @item.Color"></div>
                </td>
                <td>
                    <a asp-controller="CarSharingZones" asp-action="Details" asp-route-id=@item.Csz.Id>@Html.DisplayFor(modelItem => item.Csz.Town) @Html.DisplayFor(modelItem => item.Csz.Id)</a>
                </td>
                <td>
                    <a asp-controller="Models" asp-action="Details" asp-route-id=@item.Model.Id>@Html.DisplayFor(modelItem => item.Model.ModelName)</a>
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Редагувати</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Деталі</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Видалити</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<script>
   

    function handleSubmit(event) {
        event.preventDefault();

        const inputId = document.getElementById('UserId').value;

        const queryParams = new URLSearchParams({
            id: inputId
        });

        fetch(`SearchByUser?${queryParams.toString()}`, {
            method: 'GET',
            headers: {
                'Accept': 'application/json'
            },
        }).then(response => response.json())
            .then(data => {
                console.log(data)


                const carTable = document.getElementById('car-table');
                const children = carTable.children;

                for (let i = 0; i < children.length; i++) {
                    children[i].classList.remove('close');
                }

                for (let i = 0; i < children.length; i++) {
                    const child = children[i];
                    const childId = parseInt(child.id, 10);

                    if (!data.includes(childId)) {
                        child.classList.add('close');
                    }
                }
            })
            .catch(error => console.error('Не вдається здійснити пошук.', error));
    }
</script>

LabkaDB2/Views/Cars/CarsNotRentedByUsersWhoRentedCar.cshtml
@model IEnumerable<LabkaDB2.Models.Car>

@{
    ViewData["Title"] = "CarsNotRentedByUsersWhoRentedCar";
}

<h1>Автомобілі які орендувались користувачами, котрі орендовували певний автомобіль</h1>
<p>
    <a asp-controller="Cars" asp-action="Index">Повернутись до меню</a>
</p>
<p>
    <a asp-action="CarsNotRentedByUsersWhoRentedCar">Оновити</a>
</p>
<form id="myForm" onsubmit="handleSubmit(event)">
    <div>
        <label for="carId">Id автомобіля(number):</label>
        <input type="number" id="carId" name="carId" required>
    </div>
    <div>
        <button type="submit">Пошук</button>
    </div>
</form>
<style>
    .close {
        display: none;
    }
</style>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsRented)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProduceYear)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TechInspirationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Color)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Csz)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Model)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody id="car-table">
        @foreach (var item in Model)
        {
            <tr id=@item.Id>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsRented)
                </td>
                <td>
                    @item.ProduceYear.Year
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TechInspirationDate)
                </td>
                <td>
                    <div style="width: 15px; height: 15px; border-radius: 50%; margin-left:10px; border: 1px solid black; background: @item.Color"></div>
                </td>
                <td>
                    <a asp-controller="CarSharingZones" asp-action="Details" asp-route-id=@item.Csz.Id>@Html.DisplayFor(modelItem => item.Csz.Town) @Html.DisplayFor(modelItem => item.Csz.Id)</a>
                </td>
                <td>
                    <a asp-controller="Models" asp-action="Details" asp-route-id=@item.Model.Id>@Html.DisplayFor(modelItem => item.Model.ModelName)</a>
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Редагувати</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Деталі</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Видалити</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<script>


    function handleSubmit(event) {
        event.preventDefault();

        const inputId = document.getElementById('carId').value;

        const queryParams = new URLSearchParams({
            carId: inputId
        });

        fetch(`SearchCarsNotRentedByUsersWhoRentedCar?${queryParams.toString()}`, {
            method: 'GET',
            headers: {
                'Accept': 'application/json'
            },
        }).then(response => response.json())
            .then(data => {
                console.log(data)


                const carTable = document.getElementById('car-table');
                const children = carTable.children;

                for (let i = 0; i < children.length; i++) {
                    children[i].classList.remove('close');
                }

                for (let i = 0; i < children.length; i++) {
                    const child = children[i];
                    const childId = parseInt(child.id, 10);

                    if (!data.includes(childId)) {
                        child.classList.add('close');
                    }
                }
            })
            .catch(error => console.error('Не вдається здійснити пошук.', error));
    }
</script>