LabkaDB2/Models/Rent.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace LabkaDB2.Models;

public partial class Rent : Entity
{
    public int Id { get; set; }

    [Display(Name = "Користувач")]
    public int CustId { get; set; }
    [Display(Name = "Автомобіль")]
    public int CarId { get; set; }
    [Display(Name = "Зона каршерингу")]
    public int Cszid { get; set; }
    [Display(Name = "Дата початку")]
    public DateOnly StartDate { get; set; }
    [Display(Name = "Дата кінця")]
    public DateOnly FinishDate { get; set; }
    [Display(Name = "Добова вартість")]
    public double CostPerDay { get; set; }
    [Display(Name = "Авто")]
    public virtual Car Car { get; set; } = null!;
    [Display(Name = "Зона")]
    public virtual CarSharingZone Csz { get; set; } = null!;
    [Display(Name = "Замовник")]
    public virtual Customer Cust { get; set; } = null!;
}

LabkaDB2/Controllers/CarSharingZonesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LabkaDB2;
using LabkaDB2.Models;

namespace LabkaDB2.Controllers
{
    public class CarSharingZonesController : Controller
    {
        private readonly CarSharingDbContext _context;

        public CarSharingZonesController(CarSharingDbContext context)
        {
            _context = context;
        }

        // GET: CarSharingZones
        public async Task<IActionResult> Index()
        {
            return View(await _context.CarSharingZones.ToListAsync());
        }

        // GET: CarSharingZones/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carSharingZone = await _context.CarSharingZones
                .FirstOrDefaultAsync(m => m.Id == id);
            if (carSharingZone == null)
            {
                return NotFound();
            }

            return View(carSharingZone);
        }

        // GET: CarSharingZones/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CarSharingZones/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Town,CarCapacity,Latitude,Longtitude")] CarSharingZone carSharingZone)
        {
            if (ModelState.IsValid)
            {
                _context.Add(carSharingZone);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(carSharingZone);
        }

        // GET: CarSharingZones/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carSharingZone = await _context.CarSharingZones.FindAsync(id);
            if (carSharingZone == null)
            {
                return NotFound();
            }
            return View(carSharingZone);
        }

        // POST: CarSharingZones/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Town,CarCapacity,Latitude,Longtitude")] CarSharingZone carSharingZone)
        {
            if (id != carSharingZone.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(carSharingZone);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarSharingZoneExists(carSharingZone.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(carSharingZone);
        }

        // GET: CarSharingZones/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carSharingZone = await _context.CarSharingZones
                .FirstOrDefaultAsync(m => m.Id == id);
            if (carSharingZone == null)
            {
                return NotFound();
            }

            return View(carSharingZone);
        }

        // POST: CarSharingZones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var carSharingZone = await _context.CarSharingZones.FindAsync(id);
            if (carSharingZone != null)
            {
                _context.CarSharingZones.Remove(carSharingZone);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CarSharingZoneExists(int id)
        {
            return _context.CarSharingZones.Any(e => e.Id == id);
        }
    }
}

LabkaDB2/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LabkaDB2;
using LabkaDB2.Models;

namespace LabkaDB2.Controllers
{
    public class CarsController : Controller
    {
        private readonly CarSharingDbContext _context;

        public CarsController(CarSharingDbContext context)
        {
            _context = context;
        }

        // GET: Cars
        public async Task<IActionResult> Index()
        {
            var carSharingDbContext = _context.Cars.Include(c => c.Csz).Include(c => c.Model);
           

       
            return View(await carSharingDbContext.ToListAsync());
        }

        public async Task<IActionResult> CarsByTown()
        {
            var carSharingDbContext = _context.Cars.Include(c => c.Csz).Include(c => c.Model);



            return View(await carSharingDbContext.ToListAsync());
        }
        public async Task<IActionResult> CarsByUser()
        {
            var carSharingDbContext = _context.Cars.Include(c => c.Csz).Include(c => c.Model);



            return View(await carSharingDbContext.ToListAsync());
        }
        
        public async Task<IActionResult> CarsByBrand()
        {
            var carSharingDbContext = _context.Cars.Include(c => c.Csz).Include(c => c.Model);



            return View(await carSharingDbContext.ToListAsync());
        }


        public async Task<IActionResult> CarsNotRentedByUsersWhoRentedCar()
        {
            var carSharingDbContext = _context.Cars.Include(c => c.Csz).Include(c => c.Model);



            return View(await carSharingDbContext.ToListAsync());
        }


        public async Task<ActionResult<List<int>>> SearchByTown(string town)
        {
            var carIds = await _context.Cars
            .FromSqlRaw("SELECT c.Id FROM Cars c INNER JOIN CarSharingZones cz ON c.CSZID = cz.Id WHERE cz.Town = {0}", town)
            .Select(c => c.Id)
            .ToListAsync();

            return Json(carIds);

        }
        public async Task<ActionResult<List<Car>>> SearchCarsNotRentedByUsersWhoRentedCar(int carId)
        {
            var cars = await _context.Cars
                .FromSqlRaw(@"
                SELECT c.*
                FROM Cars c
                WHERE c.ID NOT IN (
                    SELECT DISTINCT r1.carID
                    FROM Rents r1
                    WHERE r1.custID IN (
                        SELECT r2.custID
                        FROM Rents r2
                        WHERE r2.carID = {0}
                    )
                )
            ", carId)
                .AsNoTracking()
                .Select(c=> c.Id)
                .ToListAsync();

            return Json(cars);
        }
    
    public async Task<ActionResult<List<int>>> SearchByBrand(string brand)
        {
            var carIds = await _context.Cars
            .FromSqlRaw("SELECT c.* FROM Cars c INNER JOIN Models m ON c.ModelId = m.Id WHERE m.Brand = {0}", brand)
            .Select(c => c.Id)
            .ToListAsync();

            return Json(carIds);

        }
        public async Task<ActionResult<List<int>>> SearchByUser(int id)
        {
            var carIds = await _context.Cars
            .FromSqlRaw("SELECT c.Id FROM Cars c INNER JOIN Rents r ON c.ID = r.carID WHERE r.custID = {0}", id)
            .Select(c => c.Id)
            .ToListAsync();

            return Json(carIds);

        }

        

        // GET: Cars/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Cars
                .Include(c => c.Csz)
                .Include(c => c.Model)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        public ActionResult GetAllCars()
        {
            return Json(_context.Cars);
        }

        // GET: Cars/Create
        public IActionResult Create()
        {
            ViewData["Cszid"] = new SelectList(_context.CarSharingZones.Select(c => new { Text = $"{c.Town} {c.Id}", Value = c.Id }), "Value", "Text");


            ViewData["ModelId"] = new SelectList(_context.Models.Select(c => new { Text = $"{c.ModelName} ({c.Id})", Value = c.Id }), "Value", "Text");
            
            return View();
        }

        // POST: Cars/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,ModelId,Cszid,IsRented,ProduceYear,TechInspirationDate,Color")] Car car)
        {
            ModelState.Remove("Csz");
            ModelState.Remove("Model");
            if (ModelState.IsValid)
            {
                _context.Add(car);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Cszid"] = new SelectList(_context.CarSharingZones, "Id", "Id", car.Cszid);
            ViewData["ModelId"] = new SelectList(_context.Models, "Id", "Id", car.ModelId);
            return View(car);
        }

        // GET: Cars/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Cars.FindAsync(id);
            if (car == null)
            {
                return NotFound();
            }
            
            ViewData["Cszid"] = new SelectList(_context.CarSharingZones.Select(c => new { Text = $"{c.Town} {c.Id}", Value = c.Id }), "Value", "Text");
            
            
            ViewData["ModelId"] = new SelectList(_context.Models.Select(c => new {Text = $"{c.ModelName} ({c.Id})", Value = c.Id}), "Value", "Text");
            return View(car);
        }

        // POST: Cars/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ModelId,Cszid,IsRented,ProduceYear,TechInspirationDate,Color")] Car car)
        {
            ModelState.Remove("Csz");
            ModelState.Remove("Model");

            if (id != car.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(car);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarExists(car.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Cszid"] = new SelectList(_context.CarSharingZones, "Id", "Id", car.Cszid);
            ViewData["ModelId"] = new SelectList(_context.Models, "Id", "Id", car.ModelId);
            return View(car);
        }

        // GET: Cars/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Cars
                .Include(c => c.Csz)
                .Include(c => c.Model)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // POST: Cars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var car = await _context.Cars.FindAsync(id);
            if (car != null)
            {
                _context.Cars.Remove(car);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CarExists(int id)
        {
            return _context.Cars.Any(e => e.Id == id);
        }
    }
}

LabkaDB2/Views/Rents/Create.cshtml
@model LabkaDB2.Models.Rent

@{
    ViewData["Title"] = "Create";
}

<h1>Створення</h1>

<h4>Оренда</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CustId" class="control-label"></label>
                <select asp-for="CustId" class ="form-control" asp-items="ViewBag.CustId"></select>
            </div>
            <div class="form-group">
                <label asp-for="CarId" class="control-label"></label>
                <select asp-for="CarId" class ="form-control" asp-items="ViewBag.CarId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Cszid" class="control-label"></label>
                <select asp-for="Cszid" class ="form-control" asp-items="ViewBag.Cszid"></select>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input type="date" id="StartDate" asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FinishDate" class="control-label"></label>
                <input type="date" id="FinishDate" asp-for="FinishDate" class="form-control" />
                <span asp-validation-for="FinishDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CostPerDay" class="control-label"></label>
                <input asp-for="CostPerDay" class="form-control" />
                <span asp-validation-for="CostPerDay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Створити" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад до списку</a>
</div>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const startDateInput = document.getElementById('StartDate');
        const finishDateInput = document.getElementById('FinishDate');


        


        startDateInput.addEventListener('change', function () {
            if (startDateInput.value) {
                const startDate = new Date(startDateInput.value);
                startDate.setDate(startDate.getDate() + 1);
                console.log(startDate.getDate());
                finishDateInput.min = startDate.toISOString().split('T')[0];
                finishDateInput.disabled = false;
            } else {
                finishDateInput.disabled = true;
            }
        });
    });
</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LabkaDB2/Views/Rents/Delete.cshtml
@model LabkaDB2.Models.Rent

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Ви впевнені що хочете видалити цей запис?</h3>
<div>
    <h4>Оренда</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FinishDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FinishDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CostPerDay)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CostPerDay)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Car)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Car.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Csz)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Csz.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cust)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cust.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Видалити" class="btn btn-danger" /> |
        <a asp-action="Index">Назад до списку</a>
    </form>
</div>

LabkaDB2/Views/Rents/Details.cshtml
@model LabkaDB2.Models.Rent

@{
    ViewData["Title"] = "Details";
}

<h1>Деталі</h1>

<div>
    <h4>Оренда</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FinishDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FinishDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CostPerDay)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CostPerDay)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Car)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Car.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Csz)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Csz.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cust)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cust.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Редагувати</a> |
    <a asp-action="Index">Назад до списку</a>
</div>

LabkaDB2/Views/Rents/Edit.cshtml
@model LabkaDB2.Models.Rent

@{
    ViewData["Title"] = "Edit";
}

<h1>Редагування</h1>

<h4>Оренда</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CustId" class="control-label"></label>
                <select asp-for="CustId" class="form-control" asp-items="ViewBag.CustId"></select>
                <span asp-validation-for="CustId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarId" class="control-label"></label>
                <select asp-for="CarId" class="form-control" asp-items="ViewBag.CarId"></select>
                <span asp-validation-for="CarId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cszid" class="control-label"></label>
                <select asp-for="Cszid" class="form-control" asp-items="ViewBag.Cszid"></select>
                <span asp-validation-for="Cszid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input type="date" id="StartDate" asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FinishDate" class="control-label"></label>
                <input type="date" id="FinishDate" asp-for="FinishDate" class="form-control" />
                <span asp-validation-for="FinishDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CostPerDay" class="control-label"></label>
                <input type="number" asp-for="CostPerDay" class="form-control" />
                <span asp-validation-for="CostPerDay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Зберегти" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад до списку</a>
</div>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const startDateInput = document.getElementById('StartDate');
        const finishDateInput = document.getElementById('FinishDate');


        


        startDateInput.addEventListener('change', function () {
            if (startDateInput.value) {
                const startDate = new Date(startDateInput.value);
                startDate.setDate(startDate.getDate() + 1);
                console.log(startDate.getDate());
                finishDateInput.min = startDate.toISOString().split('T')[0];
                finishDateInput.disabled = false;
            } else {
                finishDateInput.disabled = true;
            }
        });
    });
</script>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LabkaDB2/Views/Rents/Index.cshtml
@model IEnumerable<LabkaDB2.Models.Rent>

@{
    ViewData["Title"] = "Index";
}

<h1>Оренди</h1>

<p>
    <a asp-action="Create">Створити новий</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FinishDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CostPerDay)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Car)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Csz)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cust)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FinishDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CostPerDay)
            </td>
            <td>
                    <a asp-controller="Cars" asp-action="Details" asp-route-id=@item.Car.Id>@Html.DisplayFor(modelItem => item.Car.Model.ModelName) ( @Html.DisplayFor(modelItem => item.Car.Id) )</a>
            </td>
            <td>
                    <a asp-controller="CarSharingZones" asp-action="Details" asp-route-id=@item.Csz.Id>@Html.DisplayFor(modelItem => item.Csz.Town)  @Html.DisplayFor(modelItem => item.Csz.Id)</a>
            </td>
            <td>
                    <a asp-controller="Customers" asp-action="Details" asp-route-id=@item.Cust.Id>   @Html.DisplayFor(modelItem => item.Cust.FirstName) @Html.DisplayFor(modelItem => item.Cust.LastName)</a>
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Редагувати</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Деталі</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Видалити</a>
            </td>
        </tr>
}
    </tbody>
</table>